### PR TITLE
Fix #409: Add DS Algo

### LINKED ISSUE #409: Add DS Algo
I want to add resources for Data structures and Algorithms. Please assign me this issue as a part of gssoc'21.

### PR DESCRIPTION
**Pull request by shriya030**
## Explanation

Fixes #409 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] Have you followed the guidelines in the Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/CSwala/awesome-computer-science/pulls) for the same tech?
- [x] Is your submission is according to the desired pattern ?
- [x] Have you placed the contents in the `Readme.md` keeping the sorting order in mind ?
- [x] Have you placed the contents in the `Dictionary.json` keeping the sorting order in mind ?

Does you submission include -

- [x]	Category/Type
- [x]	Official Documnetation  
- [x]	Best YouTube creators  
- [x]	Useful Websites  
- [x]	Dedicated Github page 
- [x]	Best Courses  
- [x]	Ohter Tips / Hacks

### CODE REVIEW

**Comment by ddvader44** [comment]
Resolve Conflicts

**Comment by shriya030** [comment]
> Resolve Conflicts

Can you tell me how can I do that?

**Comment by shriya030** [comment]
When I click on fetch upstream in github
I get this.
This branch is 7 commits behind the upstream and has conflicts that must be resolved.
Open a pull request to fetch upstream and review changes or resolve conflicts.

**Comment by shriya030** [comment]
> Resolve Conflicts

Done!

**Comment by ddvader44** [comment]
The simplest way would be to fetch the current dictionary.json and then adding your content to it

**Comment by shriya030** [comment]
> The simplest way would be to fetch the current dictionary.json and then adding your content to it

I did that and it's done!

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
Cant review the dictionary file as around 9k lines are added and 9k are deleted , pls see to it and make sure that only the additions are there

**Comment by shriya030** [comment]
> Cant review the dictionary file as around 9k lines are added and 9k are deleted , pls see to it and make sure that only the additions are there

How should I do that?

**Comment by riturajjain2000** [comment]
> > Cant review the dictionary file as around 9k lines are added and 9k are deleted , pls see to it and make sure that only the additions are there
> 
> How should I do that?

I'll suggest use Github Desktop , so that you can see the changes clearly , and then puch the new commit using it only

**Pull request closed without merging**
