### PR TITLE
Fix #220 Added .NET

### LINKED ISSUE #220: Add .NET
Resources for learning/knowing about .NET not yet published on this repository. I want to work on this issue under GSSoC'21, also add the required gssoc'21 labels. @riturajjain2000 .

### PR DESCRIPTION
**Pull request by ibhavikamalhotra**
Fix #220 
Added the required resources for the .NET in the dictionary.json file

## Explanation
 Added the required resources for .NET in dictionary.json and this solves the mentioned issue.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] Have you followed the guidelines in the Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/CSwala/awesome-computer-science/pulls) for the same tech?
- [x] Is your submission is according to the desired pattern ?
- [x] Have you placed the contents in the `Readme.md` keeping the sorting order in mind ?

Does you submission include -

- [x]      Category/Type
- [x]      Official Documnetation  
- [x]      Best YouTube creators  
- [x]      Useful Websites  
- [x]      Dedicated Github page 
- [x]      Best Courses  
- [x]      Ohter Tips / Hacks

### CODE REVIEW

**Comment by ibhavikamalhotra** [comment]
@riturajjain2000 , Do see to it and merge this into the main branch. Please add the required labels.

**Comment by ddvader44** [comment]
good to go, @riturajjain2000 please merge this

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
Add more content as .NET is having a lot of stuff on web

**Comment by ibhavikamalhotra** [comment]
Added more content, kindly check and merge it. @ddvader44 @riturajjain2000

**Review by ddvader44 — APPROVED** [review]

**Comment by ibhavikamalhotra** [comment]
@riturajjain2000 Please see to it, I have made all the required changes, @ddvader44 has already approved the same.

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
Resolve Conflicts

**Review by riturajjain2000 — APPROVED** [review]

**Pull request merged**
