### PR TITLE
Fix #90 & Fix #87 : Add Jira and Vagrant to the Database

### LINKED ISSUE #87: Add Vagrant
See `Android` in README.md to get an idea of the contents of the PR for this issue.

### LINKED ISSUE #90: Add Jira
See `Android` in README.md to get an idea of the contents of the PR for this issue.

### PR DESCRIPTION
**Pull request by fin1te**
Fixes #90 
Fixes #87 
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "main" and not on any other branch.
- [x] Have you followed the guidelines in the Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/CSwala/awesome-computer-science/pulls) for the same tech?
- [x] Is your submission is according to the desired pattern ?
- [x] Have you placed the contents in the `Readme.md` keeping the sorting order in mind ?

Does you submission include -

- [x]	Category/Type
- [x]	Official Documnetation  
- [x]	Best YouTube creators  
- [x]	Useful Websites  
- [x]	Dedicated Github page 
- [x]	Best Courses  
- [x]	Ohter Tips / Hacks

### CODE REVIEW

**Review by ddvader44 — APPROVED** [review]
good to go, waiting for your approval @riturajjain2000

**Comment by fin1te** [comment]
@ddvader44 Added Vagrant as well.

**Comment by riturajjain2000** [comment]
Fix the Checkboxes in the PR desc. and link these 2 issues in the explanation if you are ticking the checkbox for the same !

**Comment by fin1te** [comment]
@riturajjain2000 Fixed the Checkboxes in PR Description, ( For both issues ), I'm not seeing an option to link the Issues #90 and #87 , can you link them if possible? Thanks.

**Comment by riturajjain2000** [comment]
You have to write Fixes #bugname in the description to link the issues

**Comment by fin1te** [comment]
@riturajjain2000 @ddvader44 Linked the Issues, I think all the issues are resolved with this PR now, do let me know if anything is left, Thanks! :D

**Review by riturajjain2000 — APPROVED** [review]

**Pull request merged**
