### PR TITLE
Add UX

### LINKED ISSUE #476: Add UX
See `Android` in README.md to get an idea of the contents of the PR for this issue.

### PR DESCRIPTION
**Pull request by Dishita2602**
## Explanation

Fixes #476 
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] Have you followed the guidelines in the Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/CSwala/awesome-computer-science/pulls) for the same tech?
- [x] Is your submission is according to the desired pattern ?
- [x] Have you placed the contents in the `Readme.md` keeping the sorting order in mind ?
- [x] Have you placed the contents in the `Dictionary.json` keeping the sorting order in mind ?

Does you submission include -

- [x]	Category/Type
- [x]	Official Documnetation  
- [x]	Best YouTube creators  
- [x]	Useful Websites  
- [x]	Dedicated Github page 
- [x]	Best Courses  
- [x]	Other Tips / Hacks

### CODE REVIEW

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
add more content

**Comment by Dishita2602** [comment]
Sorry to say but earlier when I had created PR regarding it only review I got was related to proper formatting and structure issue. If you want to add more content you should let me know well in advance(previous PR). I haven't change content or cut down. You should mention about all changes in review *NOT* step by step.

**Review by riturajjain2000 — APPROVED** [review]

**Comment by riturajjain2000** [comment]
> Sorry to say but earlier when I had created PR regarding it only review I got was related to proper formatting and structure issue. If you want to add more content you should let me know well in advance(previous PR). I haven't change content or cut down. You should mention about all changes in review _NOT_ step by step.

I didn't knew that adding a little more content would be so tideous for you that you will be writing a 3 liner reply .
Please don't bother , I have merged the PR. I will have someone else working on this one

**Comment by Dishita2602** [comment]
> > Sorry to say but earlier when I had created PR regarding it only review I got was related to proper formatting and structure issue. If you want to add more content you should let me know well in advance(previous PR). I haven't change content or cut down. You should mention about all changes in review _NOT_ step by step.
> 
> I didn't knew that adding a little more content would be so tideous for you that you will be writing a 3 liner reply .
> Please don't bother , I have merged the PR. I will have someone else working on this one

Thank you !!

**Pull request merged**
