### PR TITLE
Added data for 8 Topics

### LINKED ISSUE #51: Add Lua
See `Android` in README.md to get an idea of the contents of the PR for this issue.

### LINKED ISSUE #63: Add Renorex
See `Android` in README.md to get an idea of the contents of the PR for this issue.

### LINKED ISSUE #69: Add ZBrush
See `Android` in README.md to get an idea of the contents of the PR for this issue.

### LINKED ISSUE #70: Add Cinema 4D
See `Android` in README.md to get an idea of the contents of the PR for this issue.

### LINKED ISSUE #71: Add Houdini
See `Android` in README.md to get an idea of the contents of the PR for this issue.

### LINKED ISSUE #73: Add Modo
See `Android` in README.md to get an idea of the contents of the PR for this issue.

### LINKED ISSUE #74: Add Nuke
See `Android` in README.md to get an idea of the contents of the PR for this issue.

### LINKED ISSUE #75: Add Inkscape
See `Android` in README.md to get an idea of the contents of the PR for this issue.

### PR DESCRIPTION
**Pull request by fin1te**
Fixes #63 
Fixes #69 
Fixes #70 
Fixes #71 
Fixes #73 
Fixes #74 
Fixes #75 
Fixes #51 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "main" and not on any other branch.
- [x] Have you followed the guidelines in the Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/CSwala/awesome-computer-science/pulls) for the same tech?
- [x] Is your submission is according to the desired pattern ?
- [x] Have you placed the contents in the `Readme.md` keeping the sorting order in mind ?

Does you submission include -

- [x]	Category/Type
- [x]	Official Documnetation  
- [x]	Best YouTube creators  
- [x]	Useful Websites  
- [x]	Dedicated Github page 
- [x]	Best Courses  
- [x]	Ohter Tips / Hacks

### CODE REVIEW

**Comment by fin1te** [comment]
Fixed the conflict of the PR caused due to Addition of Pytorch's data

**Comment by fin1te** [comment]
Checked all my commits once, do go through all 8 commits' changes and accept the PR, thanks! :D

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
Told you to spend a good amount of time in research before making a PR !

Add more data in these , and search 'awesome tech_name' on GH and add resources from there as they have best resources for any tech 

Also split these 8 tech in 3 PRS instead of one , so that you can get proper marks

**Comment by fin1te** [comment]
Fixed the 3 conflicts due to recent PR merges on the base branch, I will be adding the extra data now, I'll ping and let you know when this issue is resolved, thanks!

**Comment by fin1te** [comment]
@riturajjain2000 Hey, Added more data for All 8 Issues as asked, Also Added **Awesome ____** GitHub repositories for All available ones, Thanks! :D

**Review by riturajjain2000 — APPROVED** [review]

**Pull request merged**
