### PR TITLE
Fix #302 Updated Dictionary.json file according to alphabetical order.

### LINKED ISSUE #302: Fix the position of `Hibernate` in Dictionary.json file
The current ordering of `Hibernate` in the Dictioanry.json file is not appropriate according to alphabetical order.
I would like to fix the ordering.

### PR DESCRIPTION
**Pull request by noviicee**
## Explanation
I have updated the Dictionary.json file according to alphabetical order of Titles.

Fixes #302 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] Have you followed the guidelines in the Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/CSwala/awesome-computer-science/pulls) for the same tech?
- [x] Is your submission is according to the desired pattern ?
- [x] Have you placed the contents in the `Readme.md` keeping the sorting order in mind ?
- [x] Have you placed the contents in the `Dictionary.json` keeping the sorting order in mind ?

### CODE REVIEW

**Review by riturajjain2000 — APPROVED** [review]

**Comment by noviicee** [comment]
Will it be counted in GSSOC?
Can you add the level tag as well as the gssoc21 tag also :)

**Comment by ddvader44** [comment]
@noviicee yes

**Comment by noviicee** [comment]
> @noviicee yes

Thanks 😃

**Comment by noviicee** [comment]
> > @noviicee yes
> 
> Thanks 😃

In the issue it is having a level-2 tag :'( 
https://github.com/CSwala/awesome-computer-science/issues/302

**Comment by noviicee** [comment]
@riturajjain2000  Thanks a lot!

**Pull request merged**
