### PR TITLE
Fixes #491: Add Competitive programming contest calendar websites

### LINKED ISSUE #491: Add Competitive programming contest calendar websites
It is useful because it shows all the contest with date,time and duration.Candidates can therefore plan there schedule beforehand.
Please assign me this issue.

### PR DESCRIPTION
**Pull request by Shivangi-ch**
## Explanation

Fixes #491 
I have added the website `clist.by`. This is a `competitive programming contest calendar website`.
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] Have you followed the guidelines in the Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/CSwala/awesome-computer-science/pulls) for the same tech?
- [x] Is your submission is according to the desired pattern ?
- [x] Have you placed the contents in the `Readme.md` keeping the sorting order in mind ?
- [x] Have you placed the contents in the `Dictionary.json` keeping the sorting order in mind ?

Does you submission include -

- [ ]	Category/Type
- [ ]	Official Documnetation  
- [ ]	Best YouTube creators  
- [x]	Useful Websites  
- [ ]	Dedicated Github page 
- [ ]	Best Courses  
- [ ]	Ohter Tips / Hacks

### CODE REVIEW

**Comment by Shivangi-ch** [comment]
@ddvader44 please review!

**Review by ddvader44 — APPROVED** [review]

**Review by riturajjain2000 — APPROVED** [review]

**Comment by riturajjain2000** [comment]
cant accept this under GSSOC , it just a nit change

**Comment by Shivangi-ch** [comment]
Why was the label for Gssoc added to the corresponding issue then. `level0` is for such minor contribution only.
I have received `level2` for even smaller changes in another projects.

**Comment by riturajjain2000** [comment]
The label was added according to the description in the issue explanation, and the work done was not that much.
Also if other Project admins are doing such things as giving level2 tags to smaller issues, then its not fair , and I'll say that provide the links for that projects on the discord server so that this point can be brought in the notice of the organising committee as it was clearly mentioned that this kind of behaviour to increase the participants scores is not acceptable

**Pull request merged**
