### PR TITLE
fix dictionary.json

### LINKED ISSUE #240: error in dictionary.json
See `Android` in README.md to get an idea of the contents of the PR for this issue.
#233 the pr is adding apache tomcat
their it is adding one extra comma 
after image link
which is causing this issue.

### PR DESCRIPTION
**Pull request by hemant2705**
## Explanation

 Fixes #240 
It is resolving the bug  present in dictionary.json file which occur due to an upstream 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [ ] Have you followed the guidelines in the Contributing document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/CSwala/awesome-computer-science/pulls) for the same tech?
- [ ] Is your submission is according to the desired pattern ?
- [ ] Have you placed the contents in the `Readme.md` keeping the sorting order in mind ?

Does you submission include -

- [ ]	Category/Type
- [ ]	Official Documnetation  
- [ ]	Best YouTube creators  
- [ ]	Useful Websites  
- [ ]	Dedicated Github page 
- [ ]	Best Courses  
- [ ]	Ohter Tips / Hacks

### CODE REVIEW

**Comment by riturajjain2000** [comment]
link the issue

**Comment by hemant2705** [comment]
#240 
its linked please check at the top

**Comment by riturajjain2000** [comment]
> #240
> its linked please check at the top

No its not , I have told many times that linking a issue means writing 'Fixes #bug-num' , its mentioned in the PR template also ,but all your PR's are without that 

so link it first

**Comment by hemant2705** [comment]
right now i cant change the pr heading 
so made changes in explantaion part

I will ensure I will go with the pr template only from next time.
Regards.

**Pull request merged**
