### PR TITLE
Added hiberante technology to the database

### LINKED ISSUE #96: Add Hibernate
See `Android` in README.md to get an idea of the contents of the PR for this issue.

### PR DESCRIPTION
**Pull request by jonathanalvares9009**
Resolved #96 

@riturajjain2000 added hibernate to the database

### CODE REVIEW

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
The info is less , see if you can find some more info.

**Comment by jonathanalvares9009** [comment]
@riturajjain2000 hibernate has a lot less information on the net

**Comment by jonathanalvares9009** [comment]
But will still try to find out?

**Comment by riturajjain2000** [comment]
> But will still try to find out?

ok

**Comment by jonathanalvares9009** [comment]
@riturajjain2000 added more info

**Review by riturajjain2000 — APPROVED** [review]

**Pull request merged**
