### PR TITLE
Fix issue #476 Add UX

### LINKED ISSUE #476: Add UX
See `Android` in README.md to get an idea of the contents of the PR for this issue.

### PR DESCRIPTION
**Pull request by Dishita2602**
## Explanation
Fixes #476 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] Have you followed the guidelines in the Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/CSwala/awesome-computer-science/pulls) for the same tech?
- [x] Is your submission is according to the desired pattern ?
- [x] Have you placed the contents in the `Readme.md` keeping the sorting order in mind ?
- [x] Have you placed the contents in the `Dictionary.json` keeping the sorting order in mind ?

Does you submission include -

- [x]	Category/Type
- [x]	Official Documnetation  
- [x]	Best YouTube creators  
- [x]	Useful Websites  
- [x]	Dedicated Github page 
- [x]	Best Courses  
- [x]	Other Tips / Hacks

### CODE REVIEW

**Comment by riturajjain2000** [comment]
Link the issue and fill the PR description

**Comment by Dishita2602** [comment]
> Link the issue and fill the PR description

Done now please review

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
dont add wiki pages as docs , and instead of YT vids , find playlist and channels . Also search for "awesome " pages on github

**Comment by Dishita2602** [comment]
Change are done you can review it

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
Why have you edited UXpin in the readme , UXpin is a tool , and UX is a development terminology

**Comment by Dishita2602** [comment]
Actually while editing I by mistakenly copy paste and made commit of UXpin tool in place of UX. After viewing file I realized and added UX. You can clearly see change more properly by viewing file

**Comment by riturajjain2000** [comment]
Yeah , but the original UXpin content is now not there

**Comment by Dishita2602** [comment]
I have done PR all on one day with different branches so content on this PR won't be there. But if you want I can add here in readme file

**Comment by riturajjain2000** [comment]
> I have done PR all on one day with different branches so content on this PR won't be there. But if you want I can add here in readme file

ok do one thing , just fetch the upstram/develop once and resolve all conflicts, as I have merged the UXpin PR , maybe that'll help in fixing this problem

**Pull request closed without merging**
