### PR TITLE
Fix issue #369 Add Deep learning

### PR DESCRIPTION
**Pull request by Dishita2602**
## Checklist

- [ y] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ y] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ y] The PR does not break any part of the existing code.
- [ y] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [ y] The PR is made to the branch that's **called** "develop".
- [ y] The PR is made from a branch that is up-to-date with "develop".
- [ y] Have you followed the guidelines in the Contributing document?
- [ y] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/CSwala/awesome-computer-science/pulls) for the same tech?
- [ y] Is your submission is according to the desired pattern ?
- [ y] Have you placed the contents in the `Readme.md` keeping the sorting order in mind ?
- [ y] Have you placed the contents in the `Dictionary.json` keeping the sorting order in mind ?

Does you submission include -

- [ y]	Category/Type
- [ y]	Official Documnetation  
- [ y]	Best YouTube creators  
- [ y]	Useful Websites  
- [ y]	Dedicated Github page 
- [ y]	Best Courses  
- [ y]Other Tips / Hacks

### CODE REVIEW

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
A lot of content is changed in dictionary , cant review . Plz make sure that only additions in deep learning are there

**Comment by Dishita2602** [comment]
> A lot of content is changed in dictionary , cant review . Plz make sure that only additions in deep learning are there

I don't know how everytime there is so much change in content. Can you please just do into Deep learning section and than check the file. I have'nt make changes in any other section @riturajjain2000

**Comment by riturajjain2000** [comment]
> > A lot of content is changed in dictionary , cant review . Plz make sure that only additions in deep learning are there
> 
> I don't know how everytime there is so much change in content. Can you please just do into Deep learning section and than check the file. I have'nt make changes in any other section @riturajjain2000

The reason is because making the changes in the PR you are not fetching the upstream,
I will review it this time , but from next time keep this is mind that you should fetch the latest upstream before changing anything

**Comment by riturajjain2000** [comment]
I checked thoroughly , there are no changes in deep learning

**Comment by Dishita2602** [comment]
> I checked thoroughly , there are no changes in deep learning

Whole content of deep learning is added by me from scratch.

**Comment by riturajjain2000** [comment]
They are not displayed here

**Pull request closed without merging**
