### PR TITLE
Fix #232 Added Apache Tomcat

### LINKED ISSUE #232: Add Apache Tomcat
@riturajjain2000 
Resources of Apache Tomcat have not been added. I would like to work on this issue.

### PR DESCRIPTION
**Pull request by ANSHIKA1806**
Fix #232
Added the required resources for the Apache Tomcat in the dictionary.json file
## Explanation

Added the required resources for Apache Tomcat in dictionary.json and this solves the mentioned issue.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] Have you followed the guidelines in the Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/CSwala/awesome-computer-science/pulls) for the same tech?
- [x] Is your submission is according to the desired pattern ?
- [x] Have you placed the contents in the `Readme.md` keeping the sorting order in mind ?

Does you submission include -

- [x]	Category/Type
- [x]	Official Documnetation  
- [x]	Best YouTube creators  
- [x]	Useful Websites  
- [x]	Dedicated Github page 
- [x]	Best Courses  
- [x]	Ohter Tips / Hacks

### CODE REVIEW

**Review by ddvader44 — CHANGES_REQUESTED** [review]
do changes in dictionary.json also

**Comment by ANSHIKA1806** [comment]
@ddvader44 
I have updated dictionary.json file alos , please check and accept my pull request.
Thank you.

**Comment by ddvader44** [comment]
@riturajjain2000 you can merge it

**Review by ddvader44 — APPROVED** [review]

**Comment by riturajjain2000** [comment]
Fix the PR description and link the issue

**Comment by ANSHIKA1806** [comment]
@riturajjain2000 
Sir , I have fixed the PR description and linked the issue. Please accept my  pull request.
Thank you.

**Review by riturajjain2000 — APPROVED** [review]

**Pull request merged**
