### PR TITLE
Fix #237 : Added Linux

### LINKED ISSUE #237: Add Linux
@riturajjain2000 @ddvader44 
Resources of Linux have not been added to this repo. I would like to work on this issue.

### PR DESCRIPTION
**Pull request by ANSHIKA1806**
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] Have you followed the guidelines in the Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/CSwala/awesome-computer-science/pulls) for the same tech?
- [x] Is your submission is according to the desired pattern ?
- [x] Have you placed the contents in the `Readme.md` keeping the sorting order in mind ?

Does you submission include -

- [x]	Category/Type
- [x]	Official Documnetation  
- [x]	Best YouTube creators  
- [x]	Useful Websites  
- [x]	Dedicated Github page 
- [x]	Best Courses  
- [x]	Other Tips / Hacks 

Issue #237

### CODE REVIEW

**Comment by ANSHIKA1806** [comment]
@ddvader44  @riturajjain2000 
Sir,
 I've added best resources for Linux to the project. Please check it and merge it.
Thank you.

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
Add more content as Linux is very popular and there is a lot of content about it on the web

**Comment by ANSHIKA1806** [comment]
@riturajjain2000  Sir, I've added some more content. Please review it and merge it to your project.

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
Still the content is very little , add more stuff!

**Comment by ddvader44** [comment]
@ANSHIKA1806 add some tips and images

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
the additions are not there in the dictionary.json Add there also

**Comment by ANSHIKA1806** [comment]
@riturajjain2000  @ddvader44 Sir I've updated readme file and dictionary.json.
Please check it and merge it to the project.

**Review by ddvader44 — CHANGES_REQUESTED** [review]
resolve merge conflicts @ANSHIKA1806

**Comment by ddvader44** [comment]
it would be good if you raise a new pr instead

**Pull request closed without merging**
