### PR TITLE
Update README.md (C++)

### PR DESCRIPTION
**Pull request by OmKhare**
C++ tab with resources added.

### CODE REVIEW

**Comment by OmKhare** [comment]
Python tab with resources added. Pls approve and merge!

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
For C++, you have added just the pages of leetcode and CodeChef in the `tips/hacks` section, you are required to add some useful links there. Also in the `category/type` section just use the term 'programming language'

**Review by riturajjain2000 — CHANGES_REQUESTED** [review]
For python, you have added just the pages of leetcode and CodeChef in the `tips/hacks` section, you are required to add some useful links there. Also in the `dedicated GitHub page` section, you are required to add pages that have curated content for python , like awesome-python.

**Comment by OmKhare** [comment]
Okay will make the required changes

**Comment by OmKhare** [comment]
Made the required changes.

**Comment by riturajjain2000** [comment]
Would love it if you could star the repo !! @OmKhare

**Pull request merged**
